# Generated by Django 2.2.14 on 2021-10-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(default='', max_length=25)),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField()),
                ('year_of_experience', models.IntegerField()),
                ('degree', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender'), ('not', 'Rather not to say')], default='male', max_length=50)),
            ],
        ),
    ]
