# Generated by Django 2.2.14 on 2021-10-19 19:52

from django.db import migrations, models
import hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctor_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to=hospital.models.PathAndRename('upload/doctor')),
        ),
    ]
