# Generated by Django 2.2.14 on 2021-10-19 19:59

from django.db import migrations, models
import hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20211020_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='uploads/doctors/profile.png', null=True, upload_to=hospital.models.PathAndRename('uploads/doctors')),
        ),
    ]
