# Generated by Django 3.2.6 on 2021-10-17 12:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.category')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('postal', models.IntegerField()),
                ('dob', models.DateField()),
                ('medical_history', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender'), ('not', 'Rather not to say')], default='male', max_length=50)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('pname', models.CharField(blank=True, default='', max_length=50)),
                ('dname', models.CharField(blank=True, default='', max_length=50)),
                ('labtime', models.CharField(choices=[('08:00 – 09:00', '08:00 – 09:00'), ('09:00 – 10:00', '09:00 – 10:00'), ('10:00 – 11:00', '10:00 – 11:00'), ('11:00 – 12:00', '11:00 – 12:00'), ('12:00 – 13:00', '12:00 – 13:00'), ('13:00 – 14:00', '13:00 – 14:00'), ('14:00 – 15:00', '14:00 – 15:00'), ('15:00 – 16:00', '15:00 – 16:00'), ('16:00 – 17:00', '16:00 – 17:00'), ('17:00 – 18:00', '17:00 – 18:00')], default='labtime', max_length=25)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.patient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.product')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursecategory', models.CharField(choices=[('Routine Checkup', 'Routine Checkup'), ('Major Health Issues', 'Major Health Issues'), ('Joint Muscle Issues', 'Joint Muscle Issues'), ('Hormonal Imbalance', 'Hormonal Imbalance'), ('Infections and rashes', 'Infections and rashes')], default='', max_length=50)),
                ('coursetopic', models.CharField(choices=[('Dr. Abhishek Wadkar - Routine Checkup', 'Dr. Abhishek Wadkar - Routine Checkup'), ('Dr. Meheka Sheikh - Routine Checkup', 'Dr. Meheka Sheikh - Routine Checkup'), ('Dr. Arvind Sagota - Routine Checkup', 'Dr. Arvind Sagota - Routine Checkup'), ('Dr. Meenal Shah - Routine Checkup', 'Dr. Meenal Shah - Routine Checkup'), ('Dr. Adrik Kaif - Routine Checkup', 'Dr. Adrik Kaif - Routine Checkup'), ('Dr. Manpreet Singh - Major Health Issues', 'Dr. Manpreet Singh - Major Health Issues'), ('Dr. Jay Sarkar - Major Health Issues', 'Dr. Jay Sarkar - Major Health Issues'), ('Dr. Aisha Manila - Major Health Issues', 'Dr. Aisha Manila - Major Health Issues'), ('Dr. Ketan Jha - Major Health Issues', 'Dr. Ketan Jha - Major Health Issues'), ('Dr. Murkh Injam - Major Health Issues', 'Dr. Murkh Injam - Major Health Issues'), ('Dr. Ashwin Mehta - Joint Muscle Issues', 'Dr. Ashwin Mehta - Joint Muscle Issues'), ('Dr. Keith Sequira - Joint Muscle Issues', 'Dr. Keith Sequira - Joint Muscle Issues'), ('Dr. Camil Dcruz - Joint Muscle Issues', 'Dr. Camil Dcruz - Joint Muscle Issues'), ('Dr. Jaya Deshmukh - Joint Muscle Issues', 'Dr. Jaya Deshmukh - Joint Muscle Issues'), ('Dr. Mandira Chopda - Joint Muscle Issues', 'Dr. Mandira Chopda - Joint Muscle Issues'), ('Dr. Aksa Pradhan - Hormonal Imbalance', 'Dr. Aksa Pradhan - Hormonal Imbalance'), ('Dr. Hritika Doshi - Hormonal Imbalance', 'Dr. Hritika Doshi - Hormonal Imbalance'), ('Dr. Misha mishra - Hormonal Imbalance', 'Dr. Misha mishra - Hormonal Imbalance'), ('Dr. Meetal Manoja - Hormonal Imbalance', 'Dr. Meetal Manoja - Hormonal Imbalance'), ('Dr. Akash Wadvani - Hormonal Imbalance', 'Dr. Akash Wadvani - Hormonal Imbalance'), ('Dr. Prem Singhania - Infections and rashes', 'Dr. Prem Singhania - Infections and rashes'), ('Dr. Kabeer Hongal - Infections and rashes', 'Dr. Kabeer Hongal - Infections and rashes'), ('Dr. Priya Narwande - Infections and rashes', 'Dr. Priya Narwande - Infections and rashes'), ('Dr. Lalita Sangikar - Infections and rashes', 'Dr. Lalita Sangikar - Infections and rashes'), ('Dr. Aditi Surekh - Infections and rashes', 'Dr. Aditi Surekh - Infections and rashes')], default='', max_length=50)),
                ('date', models.DateField()),
                ('timeslot', models.CharField(choices=[('09:00 – 10:00', '09:00 – 10:00'), ('10:00 – 11:00', '10:00 – 11:00'), ('11:00 – 12:00', '11:00 – 12:00'), ('12:00 – 13:00', '12:00 – 13:00'), ('13:00 – 14:00', '13:00 – 14:00'), ('14:00 – 15:00', '14:00 – 15:00'), ('15:00 – 16:00', '15:00 – 16:00'), ('16:00 – 17:00', '16:00 – 17:00'), ('17:00 – 18:00', '17:00 – 18:00')], default='', max_length=25)),
                ('status', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
