# Generated by Django 3.2.6 on 2021-10-23 13:06

from django.db import migrations, models
import patient.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, validators=[patient.models.validate_date]),
        ),
    ]
