# Generated by Django 3.0.5 on 2021-09-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender'), ('not', 'Rather not to say')], default='male', max_length=50),
        ),
    ]
