# Generated by Django 3.2.6 on 2021-10-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_order_labtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='pname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
