# Generated by Django 3.2.6 on 2021-10-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
