# Generated by Django 3.2.6 on 2021-10-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20211013_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='coursecategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='coursetopic',
            field=models.CharField(default='', max_length=50),
        ),
    ]
