# Generated by Django 3.2.6 on 2021-10-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20211015_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='coursecategory',
            field=models.CharField(choices=[('Routine Checkup', 'Routine Checkup'), ('Major Health Issues', 'Major Health Issues'), ('Joint Muscle Issues', 'Joint Muscle Issues'), ('Hormonal Imbalance', 'Hormonal Imbalance'), ('Infections and rashes', 'Infections and rashes')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='coursetopic',
            field=models.CharField(choices=[('Dr. Abhishek Wadkar - Routine Checkup', 'Dr. Abhishek Wadkar - Routine Checkup'), ('Dr. Meheka Sheikh - Routine Checkup', 'Dr. Meheka Sheikh - Routine Checkup'), ('Dr. Arvind Sagota - Routine Checkup', 'Dr. Arvind Sagota - Routine Checkup'), ('Dr. Meenal Shah - Routine Checkup', 'Dr. Meenal Shah - Routine Checkup'), ('Dr. Adrik Kaif - Routine Checkup', 'Dr. Adrik Kaif - Routine Checkup'), ('Dr. Manpreet Singh - Major Health Issues', 'Dr. Manpreet Singh - Major Health Issues'), ('Dr. Jay Sarkar - Major Health Issues', 'Dr. Jay Sarkar - Major Health Issues'), ('Dr. Aisha Manila - Major Health Issues', 'Dr. Aisha Manila - Major Health Issues'), ('Dr. Ketan Jha - Major Health Issues', 'Dr. Ketan Jha - Major Health Issues'), ('Dr. Murkh Injam - Major Health Issues', 'Dr. Murkh Injam - Major Health Issues'), ('Dr. Ashwin Mehta - Joint Muscle Issues', 'Dr. Ashwin Mehta - Joint Muscle Issues'), ('Dr. Keith Sequira - Joint Muscle Issues', 'Dr. Keith Sequira - Joint Muscle Issues'), ('Dr. Camil Dcruz - Joint Muscle Issues', 'Dr. Camil Dcruz - Joint Muscle Issues'), ('Dr. Jaya Deshmukh - Joint Muscle Issues', 'Dr. Jaya Deshmukh - Joint Muscle Issues'), ('Dr. Mandira Chopda - Joint Muscle Issues', 'Dr. Mandira Chopda - Joint Muscle Issues'), ('Dr. Aksa Pradhan - Hormonal Imbalance', 'Dr. Aksa Pradhan - Hormonal Imbalance'), ('Dr. Hritika Doshi - Hormonal Imbalance', 'Dr. Hritika Doshi - Hormonal Imbalance'), ('Dr. Misha mishra - Hormonal Imbalance', 'Dr. Misha mishra - Hormonal Imbalance'), ('Dr. Meetal Manoja - Hormonal Imbalance', 'Dr. Meetal Manoja - Hormonal Imbalance'), ('Dr. Akash Wadvani - Hormonal Imbalance', 'Dr. Akash Wadvani - Hormonal Imbalance'), ('Dr. Prem Singhania - Infections and rashes', 'Dr. Prem Singhania - Infections and rashes'), ('Dr. Kabeer Hongal - Infections and rashes', 'Dr. Kabeer Hongal - Infections and rashes'), ('Dr. Priya Narwande - Infections and rashes', 'Dr. Priya Narwande - Infections and rashes'), ('Dr. Lalita Sangikar - Infections and rashes', 'Dr. Lalita Sangikar - Infections and rashes'), ('Dr. Aditi Surekh - Infections and rashes', 'Dr. Aditi Surekh - Infections and rashes')], default='', max_length=50),
        ),
    ]
