# Generated by Django 3.2.6 on 2021-10-11 19:10

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_patient', models.BooleanField(default=False)),
                ('is_hospital', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], default='male', max_length=15)),
                ('address', models.CharField(default='', max_length=250)),
                ('location', models.CharField(choices=[('andheri', 'Andheri'), ('dadar', 'Dadar'), ('borivali', 'Borivali'), ('vile parle', 'Vile Parle'), ('goregaon', 'Goregaon'), ('churchgate', 'Churchgate'), ('mahim', 'Mahim'), ('grant road', 'Grant Road'), ('santacruz', 'Santacruz'), ('lower parel', 'Lower Parel'), ('sion', 'Sion')], default='location', max_length=25)),
                ('pincode', models.IntegerField()),
                ('dob', models.DateField()),
                ('history', models.CharField(default='', max_length=250)),
                ('marital_status', models.CharField(default='single', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=250)),
                ('location', models.CharField(choices=[('andheri', 'Andheri'), ('dadar', 'Dadar'), ('borivali', 'Borivali'), ('vile parle', 'Vile Parle'), ('goregaon', 'Goregaon'), ('churchgate', 'Churchgate'), ('mahim', 'Mahim'), ('grant road', 'Grant Road'), ('santacruz', 'Santacruz'), ('lower parel', 'Lower Parel'), ('sion', 'Sion')], default='location', max_length=25)),
                ('mobile', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('wards', models.IntegerField()),
                ('doctors', models.IntegerField()),
                ('tariff', models.IntegerField()),
                ('medical', models.IntegerField()),
                ('emergency', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=3)),
                ('beds', models.IntegerField()),
                ('incharge', models.CharField(default='', max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
