# Generated by Django 3.2 on 2021-10-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='emergency',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='location',
            field=models.CharField(choices=[('andheri', 'Andheri'), ('dadar', 'Dadar'), ('borivali', 'Borivali'), ('vile parle', 'Vile Parle'), ('goregaon', 'Goregaon'), ('goregaon', 'Goregaon'), ('churchgate', 'Churchgate'), ('mahim', 'Mahim'), ('grant road', 'Grant Road'), ('santacruz', 'Santacruz'), ('lower parel', 'Lower Parel'), ('sion', 'Sion')], default='location', max_length=20),
        ),
    ]
