# Generated by Django 3.2.6 on 2021-10-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='address',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='bloodgroup',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='email',
        ),
    ]
