# Generated by Django 3.2.6 on 2021-10-18 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=50)),
                ('issue', models.CharField(choices=[('Accident', 'Accident'), ('Stroke/Attack', 'Stroke/Attack'), ('Injury', 'Injury'), ('Others', 'Others')], default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('requirement', models.CharField(default='', max_length=50)),
                ('bloodgroup', models.CharField(default='', max_length=25)),
                ('address', models.CharField(default='', max_length=25)),
                ('medicine', models.CharField(default='', max_length=25)),
                ('allergy', models.CharField(default='', max_length=25)),
                ('status', models.BooleanField(default=False)),
                ('hospitalsname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
