# Generated by Django 3.2.6 on 2021-10-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_emergency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='status',
        ),
    ]
