# Generated by Django 3.2.6 on 2021-10-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_alter_emergency_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='requirement',
            field=models.CharField(choices=[('ICU', 'ICU'), ('OXYGEN CYLINDER', 'OXYGEN CYLINDER'), ('VENTILATOR', 'VENTILATOR')], default='', max_length=50),
        ),
    ]
