# Generated by Django 3.2.6 on 2021-10-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_alter_emergency_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
    ]
