# Generated by Django 3.2.6 on 2021-10-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_alter_emergency_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='allergy',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='bloodgroup',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='email',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='medicine',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
